id = "coolnight"
name = "Coolnight"
version = "0.1.0"
schema_version = 1
authors = ["Shayan <syedshayanabbas@gmail.com>"]
description = "A dark blue theme based on the coolnight colorscheme by Josean Martinez."
repository = "https://github.com/ShayanAbbas1/coolnight-zed"
